/**
 * web3-auth-svc — Cardano CIP-30 auth service for libpam-web3.
 *
 * Self-contained HTTPS server: serves the signing page and handles
 * auth callbacks.  Port is derived from the chain name via CRC32.
 * TLS uses the certs generated by the libpam-web3 postinst.
 *
 * Routes:
 *   GET  /              — Signing page HTML
 *   GET  /engine.js     — Signing page JS
 *   GET  /auth/pending/:session_id   — Return session JSON
 *   POST /auth/callback/:session_id  — Accept CIP-30 signature, write .sig file
 *
 * .sig file format (JSON):
 *   { chain, signature, public_key, otp, machine_id }
 *   chain = "cardano" — tells the PAM module which verification plugin to use
 *
 * SPECIAL profile: S7 P9 E8 C5 I7 A7 L7
 *   P9: Auth boundary — validate every input, trust nothing from the network.
 *   E8: Long-running daemon — must not crash, must not leak.
 *
 * Cryptographic verification:
 *   COSE_Sign1 Ed25519 signatures are verified before writing .sig files.
 *   This is a safety check (not forged garbage), not an identity check —
 *   the PAM plugin handles identity binding.
 */

import * as https from "node:https";
import * as fs from "node:fs";
import * as path from "node:path";
import { timingSafeEqual } from "node:crypto";
import * as cbor from "cbor";
import { ed25519 } from "@noble/curves/ed25519";
import { chainPort } from "./chain-port";

// ── Constants ──────────────────────────────────────────────────────────

const CHAIN_NAME = "cardano";
const DEFAULT_PENDING_DIR = "/run/libpam-web3/pending";
let PENDING_DIR = DEFAULT_PENDING_DIR;
const MAX_BODY_SIZE = 16_384;


const SESSION_ID_RE = /^[0-9a-f]{32}$/;
const HEX_RE = /^[0-9a-fA-F]+$/;

// ── Config ─────────────────────────────────────────────────────────────

const DEFAULT_CERT = "/etc/libpam-web3/tls/cert.pem";
const DEFAULT_KEY = "/etc/libpam-web3/tls/key.pem";
const DEFAULT_PAGES_DIR = "/usr/share/blockhost/signing-pages";

interface ServerConfig {
  port: number;
  pending_dir: string;
  cert: string;
  key: string;
  pages_dir: string;
}

function parseToml(content: string): Record<string, Record<string, unknown>> {
  const result: Record<string, Record<string, unknown>> = {};
  let section = "";

  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;

    const secMatch = line.match(/^\[([a-zA-Z_][a-zA-Z0-9_]*)\]$/);
    if (secMatch?.[1]) {
      section = secMatch[1];
      result[section] = result[section] || {};
      continue;
    }

    const kvMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+)$/);
    if (!kvMatch?.[1] || !kvMatch[2] || !section) continue;

    const key = kvMatch[1];
    const val = kvMatch[2].trim();

    if (val.startsWith('"') && val.endsWith('"')) {
      result[section]![key] = val.slice(1, -1);
    } else {
      const num = Number(val);
      result[section]![key] = Number.isNaN(num) ? val : num;
    }
  }

  return result;
}

function loadConfig(configPath: string): ServerConfig {
  const defaultPort = chainPort(CHAIN_NAME);
  const defaults: ServerConfig = {
    port: defaultPort,
    pending_dir: DEFAULT_PENDING_DIR,
    cert: DEFAULT_CERT,
    key: DEFAULT_KEY,
    pages_dir: path.join(DEFAULT_PAGES_DIR, CHAIN_NAME),
  };

  let content: string;
  try {
    content = fs.readFileSync(configPath, "utf8");
  } catch {
    return defaults;
  }

  const toml = parseToml(content);
  const sec = toml["server"] || {};

  return {
    port: typeof sec.port === "number" ? sec.port : defaults.port,
    pending_dir: String(sec.pending_dir || defaults.pending_dir),
    cert: String(sec.cert || defaults.cert),
    key: String(sec.key || defaults.key),
    pages_dir: String(sec.pages_dir || defaults.pages_dir),
  };
}

// ── Validation ────────────────────────────────────────────────────────

function isValidSessionId(id: string): boolean {
  return SESSION_ID_RE.test(id);
}

function isValidHex(str: string): boolean {
  return str.length > 0 && str.length % 2 === 0 && HEX_RE.test(str);
}

// ── Payload Types ─────────────────────────────────────────────────────

interface CallbackPayload {
  signature: string;
  key: string;
  otp: string;
  machineId: string;
}

function parseCallbackBody(body: string): CallbackPayload | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(body);
  } catch {
    return null;
  }

  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    return null;
  }

  const obj = parsed as Record<string, unknown>;
  const keys = Object.keys(obj);

  if (keys.length !== 4) return null;
  if (typeof obj["signature"] !== "string") return null;
  if (typeof obj["key"] !== "string") return null;
  if (typeof obj["otp"] !== "string") return null;
  if (typeof obj["machineId"] !== "string") return null;

  if (obj["otp"].length > 16 || obj["machineId"].length > 128) return null;

  if (!isValidHex(obj["signature"])) return null;
  if (!isValidHex(obj["key"])) return null;

  return {
    signature: obj["signature"],
    key: obj["key"],
    otp: obj["otp"],
    machineId: obj["machineId"],
  };
}

// ── Session ───────────────────────────────────────────────────────────

interface SessionData {
  otp: string;
  machine_id: string;
}

function readSession(sessionId: string): SessionData | null {
  const jsonPath = path.join(PENDING_DIR, `${sessionId}.json`);
  try {
    const content = fs.readFileSync(jsonPath, "utf8");
    const parsed: unknown = JSON.parse(content);
    if (typeof parsed !== "object" || parsed === null) return null;
    const obj = parsed as Record<string, unknown>;
    if (typeof obj["otp"] !== "string" || typeof obj["machine_id"] !== "string") {
      return null;
    }
    return { otp: obj["otp"], machine_id: obj["machine_id"] };
  } catch {
    return null;
  }
}

// ── Verification & .sig Write ─────────────────────────────────────────

interface CardanoSigFile {
  chain: "cardano";
  signature: string;
  public_key: string;
  otp: string;
  machine_id: string;
}

function validateAndWriteSig(sessionId: string, payload: CallbackPayload): string | null {
  const sigPath = path.join(PENDING_DIR, `${sessionId}.sig`);
  if (fs.existsSync(sigPath)) return "session already processed";

  const session = readSession(sessionId);
  if (!session) return "session not found or malformed";

  const otpA = Buffer.from(payload.otp);
  const otpB = Buffer.from(session.otp);
  if (otpA.length !== otpB.length) return "otp mismatch";
  if (!timingSafeEqual(otpA, otpB)) return "otp mismatch";

  if (payload.machineId !== session.machine_id) return "machine_id mismatch";

  try {
    const sigBytes = Buffer.from(payload.signature, "hex");
    const keyBytes = Buffer.from(payload.key, "hex");

    const coseSign1: unknown = cbor.decodeFirstSync(sigBytes);
    if (!Array.isArray(coseSign1) || coseSign1.length !== 4) {
      return "COSE_Sign1: invalid structure";
    }

    const [protectedHeaders, , cosePayload, signatureRaw] = coseSign1 as [
      Buffer, unknown, Buffer, Buffer
    ];

    const protectedMap: unknown = cbor.decodeFirstSync(protectedHeaders);
    if (!(protectedMap instanceof Map)) {
      return "COSE_Sign1: protected headers not a map";
    }
    const alg = protectedMap.get(1);
    if (alg !== -8) {
      return "COSE_Sign1: unexpected algorithm (expected EdDSA/-8)";
    }

    const coseKey: unknown = cbor.decodeFirstSync(keyBytes);
    if (!(coseKey instanceof Map)) {
      return "COSE_Key: not a map";
    }
    if (coseKey.get(1) !== 1)  return "COSE_Key: unexpected key type (expected OKP/1)";
    if (coseKey.get(3) !== -8) return "COSE_Key: unexpected algorithm (expected EdDSA/-8)";
    if (coseKey.get(-1) !== 6) return "COSE_Key: unexpected curve (expected Ed25519/6)";

    const publicKeyRaw = coseKey.get(-2);
    if (!(publicKeyRaw instanceof Uint8Array) || publicKeyRaw.length !== 32) {
      return "COSE_Key: missing or invalid public key bytes";
    }

    const expectedMsg = `Authenticate to ${payload.machineId} with code: ${payload.otp}`;
    const expectedBytes = Buffer.from(expectedMsg, "utf8");
    const payloadBuf = Buffer.from(cosePayload);
    if (!payloadBuf.equals(expectedBytes)) {
      return "COSE_Sign1: payload does not match expected OTP message";
    }

    const sigStructure = [
      "Signature1",
      Buffer.from(protectedHeaders),
      Buffer.alloc(0),
      payloadBuf,
    ];
    const sigStructureEncoded = cbor.encode(sigStructure) as Buffer;

    const signatureBuf = new Uint8Array(signatureRaw);
    if (signatureBuf.length !== 64) {
      return "COSE_Sign1: signature must be 64 bytes";
    }

    const valid = ed25519.verify(
      signatureBuf,
      new Uint8Array(sigStructureEncoded),
      new Uint8Array(publicKeyRaw),
    );

    if (!valid) {
      return "COSE_Sign1: Ed25519 signature verification failed";
    }
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    return `COSE verification error: ${detail}`;
  }

  const sigContent: CardanoSigFile = {
    chain: "cardano",
    signature: payload.signature,
    public_key: payload.key,
    otp: payload.otp,
    machine_id: payload.machineId,
  };

  const tmpPath = path.join(PENDING_DIR, `${sessionId}.sig.tmp`);
  try {
    fs.writeFileSync(tmpPath, JSON.stringify(sigContent));
    fs.renameSync(tmpPath, sigPath);
  } catch (err) {
    try { fs.unlinkSync(tmpPath); } catch { /* tmp may not exist */ }
    return `sig file write failed: ${err instanceof Error ? err.message : String(err)}`;
  }

  console.log(`[AUTH] Accepted CIP-30 signature for session ${sessionId}`);
  return null;
}

// ── Route Handlers ────────────────────────────────────────────────────

function sendResponse(
  res: http.ServerResponse,
  statusCode: number,
  body: string,
  contentType = "text/plain"
): void {
  res.writeHead(statusCode, { "Content-Type": contentType });
  res.end(body);
}

function handleGetPending(sessionId: string, res: http.ServerResponse): void {
  if (!isValidSessionId(sessionId)) {
    sendResponse(res, 404, "Not Found");
    return;
  }

  const jsonPath = path.join(PENDING_DIR, `${sessionId}.json`);
  let contents: string;
  try {
    contents = fs.readFileSync(jsonPath, "utf8");
  } catch {
    sendResponse(res, 404, "Not Found");
    return;
  }

  sendResponse(res, 200, contents, "application/json");
}

function handlePostCallback(
  sessionId: string,
  req: http.IncomingMessage,
  res: http.ServerResponse
): void {
  if (!isValidSessionId(sessionId)) {
    sendResponse(res, 404, "Not Found");
    return;
  }

  const contentType = req.headers["content-type"] || "";
  if (!contentType.includes("application/json")) {
    sendResponse(res, 400, "Content-Type must be application/json");
    return;
  }

  const chunks: Buffer[] = [];
  let bodySize = 0;
  let aborted = false;

  req.on("data", (chunk: Buffer) => {
    bodySize += chunk.length;
    if (bodySize > MAX_BODY_SIZE) {
      if (!aborted) {
        aborted = true;
        sendResponse(res, 413, "body too large");
        req.destroy();
      }
      return;
    }
    chunks.push(chunk);
  });

  req.on("end", () => {
    if (aborted) return;

    const body = Buffer.concat(chunks).toString("utf8").trim();
    const payload = parseCallbackBody(body);
    if (!payload) {
      sendResponse(res, 400, "invalid request body");
      return;
    }

    const error = validateAndWriteSig(sessionId, payload);

    if (error === null) {
      sendResponse(res, 200, "OK");
    } else if (error === "session already processed") {
      sendResponse(res, 409, "Conflict");
    } else if (error === "session not found or malformed") {
      sendResponse(res, 404, "Not Found");
    } else {
      console.error(`[AUTH] Callback rejected for session ${sessionId}: ${error}`);
      sendResponse(res, 400, "verification failed");
    }
  });

  req.on("error", () => { /* connection closed by client */ });
}

// ── Static file serving ───────────────────────────────────────────────

let PAGES_DIR = "";

function serveFile(
  res: https.ServerResponse<import("node:http").IncomingMessage>,
  filePath: string,
  contentType: string
): void {
  let data: Buffer;
  try {
    data = fs.readFileSync(filePath);
  } catch {
    sendResponse(res, 404, "Not Found");
    return;
  }
  res.writeHead(200, {
    "Content-Type": contentType,
    "Content-Length": data.length,
  });
  res.end(data);
}

// ── Server ────────────────────────────────────────────────────────────

function main(): void {
  const configPath = process.argv[2] || `/etc/web3-auth/${CHAIN_NAME}.toml`;
  const config = loadConfig(configPath);
  PENDING_DIR = config.pending_dir;
  PAGES_DIR = config.pages_dir;

  let tlsOpts: { cert: Buffer; key: Buffer };
  try {
    tlsOpts = {
      cert: fs.readFileSync(config.cert),
      key: fs.readFileSync(config.key),
    };
  } catch (err) {
    console.error(`[AUTH] TLS cert/key load failed: ${err}`);
    process.exit(1);
  }

  const server = https.createServer(tlsOpts, (req, res) => {
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("Cache-Control", "no-store");

    const url = new URL(req.url || "/", "https://localhost");
    const pathname = url.pathname;

    // Signing page
    if (req.method === "GET" && (pathname === "/" || pathname === "/index.html")) {
      serveFile(res, path.join(PAGES_DIR, "index.html"), "text/html; charset=utf-8");
      return;
    }
    if (req.method === "GET" && pathname === "/engine.js") {
      serveFile(res, path.join(PAGES_DIR, "engine.js"), "application/javascript; charset=utf-8");
      return;
    }

    // Auth API
    const pendingMatch = pathname.match(/^\/auth\/pending\/([^/]+)$/);
    if (req.method === "GET" && pendingMatch?.[1]) {
      handleGetPending(pendingMatch[1], res);
      return;
    }

    const callbackMatch = pathname.match(/^\/auth\/callback\/([^/]+)$/);
    if (req.method === "POST" && callbackMatch?.[1]) {
      handlePostCallback(callbackMatch[1], req, res);
      return;
    }

    sendResponse(res, 404, "Not Found");
  });

  // Bind to all interfaces (dual-stack IPv6)
  server.listen(config.port, "::", () => {
    console.log(`[AUTH] web3-auth-svc (${CHAIN_NAME}) on [::]:${config.port}`);
    console.log(`[AUTH] Pending dir: ${PENDING_DIR}`);
    console.log(`[AUTH] Pages: ${PAGES_DIR}`);
  });

  server.on("error", (err) => {
    console.error(`[AUTH] Server error: ${err}`);
    process.exit(1);
  });

  process.on("SIGTERM", () => {
    console.log("[AUTH] Shutting down...");
    server.close(() => process.exit(0));
  });

  process.on("SIGINT", () => {
    console.log("[AUTH] Shutting down...");
    server.close(() => process.exit(0));
  });
}

// Only run as a server when invoked as the entry point (auth-svc.js or
// index.ts via tsx). When imported by a test file, skip — otherwise the
// test would try to load TLS certs and bind to a port.
if (process.argv[1]?.match(/\/(auth-svc\.js|index\.ts)$/)) {
  main();
}
